name: illumina-assembly-snake
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - bioconda::snakemake=7.8.5
  - bioconda::pilon=1.2.4
  - bioconda::spades=3.15.5
  - bioconda::shovill=1.1.0
  - bioconda::skesa=2.4.0

